# Generated by Django 5.0.2 on 2024-02-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedperson',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
