# Generated by Django 5.0.2 on 2024-03-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_remove_child_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='color_code',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
