# Generated by Django 5.0.2 on 2024-05-23 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_feepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='taskapp.child'),
        ),
    ]
