# Generated by Django 5.0.2 on 2024-05-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_feepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='payment_dates',
            new_name='payment_entries',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='paid_amount',
        ),
    ]
