# Generated by Django 5.0.2 on 2024-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_rename_payment_dates_feepayment_payment_entries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cancelled_dates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
